<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CS2LineupFinder.Core</AssemblyName>
    <RootNamespace>CS2LineupFinder.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\contracts\*.cs" LinkBase="Contracts" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
</Project>
