<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CS2LineupFinder.Core</AssemblyName>
    <RootNamespace>CS2LineupFinder.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\contracts\CS2LineupFinder.Abstractions.csproj" />
  </ItemGroup>
</Project>
